server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: employee-service
              uri: http://employee-service:8081
              predicates:
                - Path=/employee/**
